theme: jekyll-theme-minimal
theme: jekyll-theme-minimal
title: Functional to-do app
logo: /assets/ic_launcher-web.png
description: Functional is a free and open source to-do (task) app.
show_downloads: false
